version: '3.7'

networks:
  php8-network:
    driver: bridge

services:
  web:
    build: ./.docker
    working_dir: /var/www
    restart: always
    container_name: php8-web
    networks:
      - php8-network
    depends_on:
      - mysql
      # - postgres
      # - redis
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./.docker/apache/vhosts/localhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/apache/vhosts/localhost-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DOCUMENT_ROOT=/var/www/public_html
      - APACHE_LOG_DIR=/var/www/.docker/apache/logs

  mysql:
    image: mysql:5.7
    restart: always
    container_name: php8-mysql
    networks:
      - php8-network
    ports:
      - '3306:3306'
    volumes:
      - './.docker/mysql/config:/etc/mysql/conf.d'
      - './.docker/mysql/database:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    container_name: php8-phpmyadmin
  #    networks:
  #      - php8-network
  #    depends_on:
  #      - mysql
  #    environment:
  #      PMA_HOST: mysql
  #      PMA_PORT: 3306
  #    ports:
  #      - '8080:80'

  #  postgres:
  #    image: postgres:alpine
  #    container_name: php8-postgres
  #    restart: always
  #    networks:
  #      - php8-network
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - './.docker/postgres:/var/lib/postgresql/data'
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=root
  #      - POSTGRES_DB=development

  #  redis:
  #    image: bitnami/redis:latest
  #    restart: always
  #    container_name: php8-redis
  #    volumes:
  #      - ./.docker/redis:/bitnami/redis/data
  #    networks:
  #      - php8-network
  #    environment:
  #      - ALLOW_EMPTY_PASSWORD=no
  #      - REDIS_PASSWORD=root
  #    ports:
  #      - '6379:6379'
